#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""GearPick v6.0 新增品类生成器：显示器 / 电竞椅 / 外设配件。

口径沿用 v5.0：公开目录型号，价格与参数统一标待核实；每条必须带可公开搜索的来源。
运行后直接更新 gear/products.json；随后必须执行 node tools/embed_products.js。
"""
import json
import os
from urllib.parse import quote


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PRODUCTS_PATH = os.path.join(ROOT, "products.json")


OFFICIAL = {
    "LG": "https://www.lg.com/us/monitors",
    "Samsung": "https://www.samsung.com/us/computing/monitors/",
    "Dell": "https://www.dell.com/en-us/shop/monitors/",
    "Alienware": "https://www.dell.com/en-us/shop/gaming-and-games/alienware-monitors/",
    "AOC": "https://www.aoc.com/en-us/monitors",
    "ASUS": "https://www.asus.com/displays-desktops/monitors/",
    "ROG": "https://rog.asus.com/monitors/",
    "TUF": "https://www.asus.com/displays-desktops/monitors/tuf-gaming-monitors/",
    "MSI": "https://www.msi.com/Monitors",
    "Gigabyte": "https://www.gigabyte.com/Monitor",
    "AORUS": "https://www.aorus.com/monitors",
    "Acer": "https://www.acer.com/us-en/monitors",
    "Predator": "https://www.acer.com/us-en/predator/monitors",
    "Nitro": "https://www.acer.com/us-en/nitro/monitors",
    "BenQ": "https://www.benq.com/en-us/monitor.html",
    "ZOWIE": "https://zowie.benq.com/en/products/monitors.html",
    "HP": "https://www.hp.com/us-en/shop/vwa/monitors",
    "Omen": "https://www.omen.com/us/en/monitors.html",
    "ViewSonic": "https://www.viewsonic.com/us/products/monitors",
    "Philips": "https://www.philips.com/c-m-so/monitors",
    "KTC": "https://www.ktc.com/",
    "Xiaomi": "https://www.mi.com/global/product/monitors",
    "Redmi": "https://www.mi.com/global/product/monitors",
    "HKC": "https://www.hkcofficial.com/",
    "Innocn": "https://www.innocn.com/",
    "Secretlab": "https://secretlab.co/",
    "Herman Miller": "https://www.hermanmiller.com/en_us/seating/",
    "Steelcase": "https://www.steelcase.com/products/office-chairs/",
    "Humanscale": "https://www.humanscale.com/products/office-chairs",
    "Razer": "https://www.razer.com/pc/gaming-chairs",
    "Corsair": "https://www.corsair.com/us/en/gaming-chairs",
    "AndaSeat": "https://andaseat.com/",
    "DXRacer": "https://www.dxracer.com/",
    "Noblechairs": "https://www.noblechairs.com/",
    "Autonomous": "https://www.autonomous.ai/office-chairs",
    "Branch": "https://branchfurniture.com/",
    "Sihoo": "https://www.sihoo.com/",
    "Hbada": "https://www.hbada.com/",
    "IKEA": "https://www.ikea.com/us/en/cat/office-chairs-14615/",
    "Ergotron": "https://www.ergotron.com/en-us/products/monitor-arms",
    "Logitech": "https://www.logitech.com/en-us/products/webcams.html",
    "Elgato": "https://www.elgato.com/us/en/capture",
    "Rode": "https://rode.com/en/microphones/accessories",
    "Blue": "https://www.bluemic.com/en-us/products/compass/",
    "BenQ ScreenBar": "https://www.benq.com/en-us/lighting/",
}


def jd_source(brand, name):
    q = quote("{} {}".format(brand, name).strip())
    return "https://search.jd.com/Search?keyword=" + q


def source_for(brand):
    return OFFICIAL.get(brand)


def mk_item(prefix, idx, name, brand, tier, type_, size=None):
    src = source_for(brand) or jd_source(brand, name)
    item = {
        "id": "{}-{:04d}".format(prefix, idx + 1),
        "name": name,
        "brand": brand,
        "price": None,
        "price_note": "价格待核实",
        "price_verified_at": None,
        "category": tier,
        "budget_tier": tier,
        "best_for": [],
        "caveat": "公开目录收录，参数待核实",
        "source": src,
        "sources": [
            {"type": "ecommerce", "label": "品牌官网/电商搜索入口", "url": src}
        ],
        "recommend_reason": ["公开目录收录：型号待核实，价格与参数待补充"],
        "notes": ["型号来自公开目录/搜索入口，未逐一核实"],
        "verification_status": "待核实",
        "type": type_,
    }
    if size:
        item["size"] = size
    return item


MONITORS = [
    ("LG UltraGear 24GN600", "LG", "入门", "24英寸", "电竞显示器"),
    ("LG UltraGear 24GN650", "LG", "入门", "24英寸", "电竞显示器"),
    ("LG UltraGear 24GQ50B", "LG", "入门", "24英寸", "电竞显示器"),
    ("LG UltraGear 27GN600", "LG", "入门", "27英寸", "电竞显示器"),
    ("LG UltraGear 27GN650", "LG", "入门", "27英寸", "电竞显示器"),
    ("LG UltraGear 27GN800", "LG", "中端", "27英寸", "电竞显示器"),
    ("LG UltraGear 27GN850", "LG", "中端", "27英寸", "电竞显示器"),
    ("LG UltraGear 27GP850", "LG", "中高端", "27英寸", "电竞显示器"),
    ("LG UltraGear 27GP95U", "LG", "高端", "27英寸", "电竞显示器"),
    ("LG UltraGear 27GN950", "LG", "高端", "27英寸", "电竞显示器"),
    ("LG UltraGear 27GS75Q", "LG", "中端", "27英寸", "电竞显示器"),
    ("LG UltraGear 27GS95QE", "LG", "高端", "27英寸", "OLED电竞显示器"),
    ("LG UltraGear 27GR95QE", "LG", "高端", "27英寸", "OLED电竞显示器"),
    ("LG UltraGear 32GN600", "LG", "中端", "32英寸", "电竞显示器"),
    ("LG UltraGear 32GN650", "LG", "中端", "32英寸", "电竞显示器"),
    ("LG UltraGear 32GP850", "LG", "中高端", "32英寸", "电竞显示器"),
    ("LG UltraGear 32GQ950", "LG", "高端", "32英寸", "电竞显示器"),
    ("LG UltraGear 32GS95UE", "LG", "旗舰", "32英寸", "OLED电竞显示器"),
    ("LG UltraGear 34GN850", "LG", "高端", "34英寸", "曲面电竞显示器"),
    ("LG UltraGear 34GS95QE", "LG", "旗舰", "34英寸", "OLED曲面电竞显示器"),
    ("LG UltraGear 38GN950", "LG", "旗舰", "38英寸", "曲面电竞显示器"),
    ("LG UltraGear 39GS95QE", "LG", "旗舰", "39英寸", "OLED曲面电竞显示器"),
    ("LG UltraGear 45GS95QE", "LG", "旗舰", "45英寸", "OLED曲面电竞显示器"),
    ("LG UltraGear 45GS95QB", "LG", "旗舰", "45英寸", "OLED曲面电竞显示器"),
    ("LG UltraGear 48GQ900", "LG", "旗舰", "48英寸", "OLED电竞显示器"),
    ("LG UltraWide 29WN600", "LG", "入门", "29英寸", "办公显示器"),
    ("LG UltraWide 34WP65C", "LG", "中端", "34英寸", "曲面办公显示器"),
    ("LG UltraWide 35WN75C", "LG", "中高端", "35英寸", "曲面办公显示器"),
    ("LG UltraWide 38WN95C", "LG", "旗舰", "38英寸", "曲面办公显示器"),
    ("LG UltraFine 27UP850N", "LG", "中高端", "27英寸", "办公显示器"),
    ("LG UltraFine 27UQ850", "LG", "中高端", "27英寸", "办公显示器"),
    ("LG UltraFine 32UN880", "LG", "高端", "32英寸", "办公显示器"),
    ("Samsung Odyssey G3 24", "Samsung", "入门", "24英寸", "电竞显示器"),
    ("Samsung Odyssey G3 27", "Samsung", "入门", "27英寸", "电竞显示器"),
    ("Samsung Odyssey G30A 24", "Samsung", "入门", "24英寸", "电竞显示器"),
    ("Samsung Odyssey G30A 27", "Samsung", "入门", "27英寸", "电竞显示器"),
    ("Samsung Odyssey G40E 24", "Samsung", "入门", "24英寸", "电竞显示器"),
    ("Samsung Odyssey G40E 27", "Samsung", "中端", "27英寸", "电竞显示器"),
    ("Samsung Odyssey G4 25", "Samsung", "中端", "25英寸", "电竞显示器"),
    ("Samsung Odyssey G50A 27", "Samsung", "中端", "27英寸", "电竞显示器"),
    ("Samsung Odyssey G50A 32", "Samsung", "中端", "32英寸", "电竞显示器"),
    ("Samsung Odyssey G5 27", "Samsung", "中端", "27英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G5 32", "Samsung", "中端", "32英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G5 34", "Samsung", "中高端", "34英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G55A 27", "Samsung", "中端", "27英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G55A 32", "Samsung", "中端", "32英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G6 27", "Samsung", "中高端", "27英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G6 32", "Samsung", "中高端", "32英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G65B 27", "Samsung", "中高端", "27英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G7 27", "Samsung", "高端", "27英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G7 32", "Samsung", "高端", "32英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G75T 27", "Samsung", "高端", "27英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G75T 32", "Samsung", "高端", "32英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G8 32", "Samsung", "旗舰", "32英寸", "OLED电竞显示器"),
    ("Samsung Odyssey G80SD 27", "Samsung", "高端", "27英寸", "OLED电竞显示器"),
    ("Samsung Odyssey G80SD 32", "Samsung", "旗舰", "32英寸", "OLED电竞显示器"),
    ("Samsung Odyssey G85B 32", "Samsung", "高端", "32英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G85B 34", "Samsung", "高端", "34英寸", "曲面电竞显示器"),
    ("Samsung Odyssey G9 49", "Samsung", "旗舰", "49英寸", "超宽曲面电竞显示器"),
    ("Samsung Odyssey G90T 49", "Samsung", "旗舰", "49英寸", "超宽曲面电竞显示器"),
    ("Samsung Odyssey G95T 49", "Samsung", "旗舰", "49英寸", "超宽曲面电竞显示器"),
    ("Samsung Odyssey G95C 49", "Samsung", "旗舰", "49英寸", "超宽曲面电竞显示器"),
    ("Samsung Odyssey G97T 57", "Samsung", "旗舰", "57英寸", "超宽曲面电竞显示器"),
    ("Samsung Odyssey Ark 55", "Samsung", "旗舰", "55英寸", "曲面电竞显示器"),
    ("Samsung Smart Monitor M7 32", "Samsung", "中高端", "32英寸", "办公显示器"),
    ("Samsung Smart Monitor M8 32", "Samsung", "高端", "32英寸", "办公显示器"),
    ("Samsung ViewFinity S5 27", "Samsung", "中端", "27英寸", "办公显示器"),
    ("Samsung ViewFinity S6 27", "Samsung", "中端", "27英寸", "办公显示器"),
    ("Samsung ViewFinity S7 32", "Samsung", "中高端", "32英寸", "办公显示器"),
    ("Samsung ViewFinity S8 27", "Samsung", "中高端", "27英寸", "办公显示器"),
    ("Dell S2421H", "Dell", "入门", "24英寸", "办公显示器"),
    ("Dell S2422HZ", "Dell", "入门", "24英寸", "办公显示器"),
    ("Dell S2721H", "Dell", "入门", "27英寸", "办公显示器"),
    ("Dell S2721QS", "Dell", "中端", "27英寸", "办公显示器"),
    ("Dell S2721DGF", "Dell", "中高端", "27英寸", "电竞显示器"),
    ("Dell S3221QS", "Dell", "中高端", "32英寸", "曲面办公显示器"),
    ("Dell S3422DWG", "Dell", "高端", "34英寸", "曲面电竞显示器"),
    ("Dell G2422HS", "Dell", "入门", "24英寸", "电竞显示器"),
    ("Dell G2722HS", "Dell", "入门", "27英寸", "电竞显示器"),
    ("Dell G2723H", "Dell", "入门", "27英寸", "电竞显示器"),
    ("Dell G2724D", "Dell", "中端", "27英寸", "电竞显示器"),
    ("Dell G3223D", "Dell", "中高端", "32英寸", "电竞显示器"),
    ("Dell G3223Q", "Dell", "高端", "32英寸", "电竞显示器"),
    ("Dell U2422H", "Dell", "中端", "24英寸", "办公显示器"),
    ("Dell U2723QE", "Dell", "中高端", "27英寸", "办公显示器"),
    ("Dell U2724D", "Dell", "中高端", "27英寸", "办公显示器"),
    ("Dell U3223QE", "Dell", "高端", "32英寸", "办公显示器"),
    ("Dell U4025QW", "Dell", "旗舰", "40英寸", "曲面办公显示器"),
    ("Dell UltraSharp 24 USB-C Hub", "Dell", "中端", "24英寸", "办公显示器"),
    ("Dell UltraSharp 27 4K", "Dell", "中高端", "27英寸", "办公显示器"),
    ("Dell UltraSharp 32 6K", "Dell", "旗舰", "32英寸", "办公显示器"),
    ("Alienware AW2518HF", "Alienware", "中端", "25英寸", "电竞显示器"),
    ("Alienware AW2521HF", "Alienware", "中端", "25英寸", "电竞显示器"),
    ("Alienware AW2523HF", "Alienware", "中高端", "25英寸", "电竞显示器"),
    ("Alienware AW2524HF", "Alienware", "高端", "25英寸", "电竞显示器"),
    ("Alienware AW2720HF", "Alienware", "中端", "27英寸", "电竞显示器"),
    ("Alienware AW2721D", "Alienware", "高端", "27英寸", "电竞显示器"),
    ("Alienware AW2723DF", "Alienware", "高端", "27英寸", "电竞显示器"),
    ("Alienware AW2725DF", "Alienware", "旗舰", "27英寸", "OLED电竞显示器"),
    ("Alienware AW3225QF", "Alienware", "旗舰", "32英寸", "OLED电竞显示器"),
    ("Alienware AW3423DW", "Alienware", "旗舰", "34英寸", "OLED曲面电竞显示器"),
    ("Alienware AW3423DWF", "Alienware", "旗舰", "34英寸", "OLED曲面电竞显示器"),
    ("Alienware AW3821DW", "Alienware", "旗舰", "38英寸", "曲面电竞显示器"),
    ("Alienware AW5520QF", "Alienware", "旗舰", "55英寸", "电竞显示器"),
    ("AOC 24G2", "AOC", "入门", "24英寸", "电竞显示器"),
    ("AOC 24G2SP", "AOC", "入门", "24英寸", "电竞显示器"),
    ("AOC 24G4", "AOC", "入门", "24英寸", "电竞显示器"),
    ("AOC 27G2", "AOC", "入门", "27英寸", "电竞显示器"),
    ("AOC 27G2SP", "AOC", "入门", "27英寸", "电竞显示器"),
    ("AOC 27G4", "AOC", "入门", "27英寸", "电竞显示器"),
    ("AOC 27G3", "AOC", "中端", "27英寸", "电竞显示器"),
    ("AOC 27G3X", "AOC", "中端", "27英寸", "电竞显示器"),
    ("AOC 27G3XN", "AOC", "中端", "27英寸", "电竞显示器"),
    ("AOC Q27G2S", "AOC", "中端", "27英寸", "电竞显示器"),
    ("AOC Q27G3XMN", "AOC", "中高端", "27英寸", "电竞显示器"),
    ("AOC Q27G4X", "AOC", "中高端", "27英寸", "电竞显示器"),
    ("AOC 32G2SE", "AOC", "中端", "32英寸", "曲面电竞显示器"),
    ("AOC 32G3", "AOC", "中端", "32英寸", "曲面电竞显示器"),
    ("AOC CQ32G3SE", "AOC", "中端", "32英寸", "曲面电竞显示器"),
    ("AOC CU34G2XP", "AOC", "中高端", "34英寸", "曲面电竞显示器"),
    ("AOC AG246FK", "AOC", "高端", "24英寸", "电竞显示器"),
    ("AOC AG256FK", "AOC", "高端", "25英寸", "电竞显示器"),
    ("AOC AG276FK", "AOC", "高端", "27英寸", "电竞显示器"),
    ("AOC AG276QZD", "AOC", "旗舰", "27英寸", "OLED电竞显示器"),
    ("AOC AG326UD", "AOC", "旗舰", "32英寸", "OLED电竞显示器"),
    ("AOC AGON AG493UCX2", "AOC", "旗舰", "49英寸", "超宽曲面电竞显示器"),
    ("AOC 24V2Q", "AOC", "入门", "24英寸", "办公显示器"),
    ("AOC 27V5", "AOC", "入门", "27英寸", "办公显示器"),
    ("AOC 27VQ1A", "AOC", "入门", "27英寸", "办公显示器"),
    ("ASUS TUF VG249Q1A", "TUF", "入门", "24英寸", "电竞显示器"),
    ("ASUS TUF VG249Q", "TUF", "入门", "24英寸", "电竞显示器"),
    ("ASUS TUF VG259QM", "TUF", "中端", "25英寸", "电竞显示器"),
    ("ASUS TUF VG259QR", "TUF", "中端", "25英寸", "电竞显示器"),
    ("ASUS TUF VG27AQ", "TUF", "中端", "27英寸", "电竞显示器"),
    ("ASUS TUF VG27AQ1A", "TUF", "中端", "27英寸", "电竞显示器"),
    ("ASUS TUF VG27AQ3A", "TUF", "中端", "27英寸", "电竞显示器"),
    ("ASUS TUF VG27AQML1A", "TUF", "中高端", "27英寸", "电竞显示器"),
    ("ASUS TUF VG27AQL3A", "TUF", "中高端", "27英寸", "电竞显示器"),
    ("ASUS TUF VG27WQ1B", "TUF", "中端", "27英寸", "曲面电竞显示器"),
    ("ASUS TUF VG32AQL1A", "TUF", "中高端", "32英寸", "电竞显示器"),
    ("ASUS TUF VG34VQL1A", "TUF", "中高端", "34英寸", "曲面电竞显示器"),
    ("ASUS TUF VG278QR", "TUF", "中端", "27英寸", "电竞显示器"),
    ("ASUS ROG Swift PG248QP", "ROG", "高端", "24英寸", "电竞显示器"),
    ("ASUS ROG Swift PG259QNR", "ROG", "高端", "25英寸", "电竞显示器"),
    ("ASUS ROG Swift PG27AQN", "ROG", "高端", "27英寸", "电竞显示器"),
    ("ASUS ROG Swift PG27AQDM", "ROG", "旗舰", "27英寸", "OLED电竞显示器"),
    ("ASUS ROG Swift PG32UCDM", "ROG", "旗舰", "32英寸", "OLED电竞显示器"),
    ("ASUS ROG Swift PG32UQXR", "ROG", "高端", "32英寸", "电竞显示器"),
    ("ASUS ROG Swift PG34WCDM", "ROG", "旗舰", "34英寸", "OLED曲面电竞显示器"),
    ("ASUS ROG Swift PG42UQ", "ROG", "旗舰", "42英寸", "OLED电竞显示器"),
    ("ASUS ROG Swift PG48UQ", "ROG", "旗舰", "48英寸", "OLED电竞显示器"),
    ("ASUS ROG Strix XG249CM", "ROG", "中端", "24英寸", "电竞显示器"),
    ("ASUS ROG Strix XG259CM", "ROG", "中端", "25英寸", "电竞显示器"),
    ("ASUS ROG Strix XG27ACS", "ROG", "中高端", "27英寸", "电竞显示器"),
    ("ASUS ROG Strix XG27AQM", "ROG", "高端", "27英寸", "电竞显示器"),
    ("ASUS ROG Strix XG27AQMR", "ROG", "高端", "27英寸", "电竞显示器"),
    ("ASUS ROG Strix XG27AQV", "ROG", "中高端", "27英寸", "电竞显示器"),
    ("ASUS ROG Strix XG32AQ", "ROG", "高端", "32英寸", "电竞显示器"),
    ("ASUS ROG Strix XG32UQ", "ROG", "高端", "32英寸", "电竞显示器"),
    ("ASUS ROG Strix XG349C", "ROG", "高端", "34英寸", "曲面电竞显示器"),
    ("ASUS ProArt PA278QV", "ASUS", "中端", "27英寸", "办公显示器"),
    ("ASUS ProArt PA279CV", "ASUS", "中高端", "27英寸", "办公显示器"),
    ("ASUS ProArt PA32UCX", "ASUS", "旗舰", "32英寸", "办公显示器"),
    ("MSI G2412", "MSI", "入门", "24英寸", "电竞显示器"),
    ("MSI G2422", "MSI", "入门", "24英寸", "电竞显示器"),
    ("MSI G255F", "MSI", "入门", "25英寸", "电竞显示器"),
    ("MSI G274F", "MSI", "入门", "27英寸", "电竞显示器"),
    ("MSI G272QPF", "MSI", "中端", "27英寸", "电竞显示器"),
    ("MSI G274QPF", "MSI", "中端", "27英寸", "电竞显示器"),
    ("MSI G274QPX", "MSI", "中高端", "27英寸", "电竞显示器"),
    ("MSI MAG 274QRF", "MSI", "中端", "27英寸", "电竞显示器"),
    ("MSI MAG 274QRF-QD", "MSI", "中高端", "27英寸", "电竞显示器"),
    ("MSI MAG 274UPF", "MSI", "中高端", "27英寸", "电竞显示器"),
    ("MSI MAG 271QPX", "MSI", "中高端", "27英寸", "电竞显示器"),
    ("MSI MAG 274QRX", "MSI", "中高端", "27英寸", "电竞显示器"),
    ("MSI MAG 274CQRF", "MSI", "中端", "27英寸", "曲面电竞显示器"),
    ("MSI MAG 321UP", "MSI", "中高端", "32英寸", "电竞显示器"),
    ("MSI MAG 323UPF", "MSI", "高端", "32英寸", "电竞显示器"),
    ("MSI MAG 341CQP", "MSI", "高端", "34英寸", "曲面电竞显示器"),
    ("MSI MPG 271QRX", "MSI", "旗舰", "27英寸", "OLED电竞显示器"),
    ("MSI MPG 321UR-QD", "MSI", "高端", "32英寸", "电竞显示器"),
    ("MSI MPG 341CQPX", "MSI", "高端", "34英寸", "曲面电竞显示器"),
    ("MSI MPG 491CQP", "MSI", "旗舰", "49英寸", "超宽曲面电竞显示器"),
    ("MSI MEG 381CQR", "MSI", "旗舰", "38英寸", "曲面电竞显示器"),
    ("MSI MEG 381KQR", "MSI", "旗舰", "38英寸", "曲面电竞显示器"),
    ("MSI G27C4", "MSI", "入门", "27英寸", "曲面电竞显示器"),
    ("Gigabyte G24F", "Gigabyte", "入门", "24英寸", "电竞显示器"),
    ("Gigabyte G24F2", "Gigabyte", "入门", "24英寸", "电竞显示器"),
    ("Gigabyte G27F2", "Gigabyte", "入门", "27英寸", "电竞显示器"),
    ("Gigabyte G27Q", "Gigabyte", "中端", "27英寸", "电竞显示器"),
    ("Gigabyte G27QC", "Gigabyte", "中端", "27英寸", "曲面电竞显示器"),
    ("Gigabyte G32QC", "Gigabyte", "中端", "32英寸", "曲面电竞显示器"),
    ("Gigabyte G34WQC", "Gigabyte", "中高端", "34英寸", "曲面电竞显示器"),
    ("Gigabyte M27Q", "Gigabyte", "中端", "27英寸", "电竞显示器"),
    ("Gigabyte M27Q P", "Gigabyte", "中高端", "27英寸", "电竞显示器"),
    ("Gigabyte M27Q X", "Gigabyte", "中高端", "27英寸", "电竞显示器"),
    ("Gigabyte M28U", "Gigabyte", "中高端", "28英寸", "电竞显示器"),
    ("Gigabyte M32U", "Gigabyte", "高端", "32英寸", "电竞显示器"),
    ("Gigabyte M32UC", "Gigabyte", "中高端", "32英寸", "曲面电竞显示器"),
    ("Gigabyte M34WQ", "Gigabyte", "中高端", "34英寸", "电竞显示器"),
    ("Gigabyte FI32U", "Gigabyte", "高端", "32英寸", "电竞显示器"),
    ("Gigabyte FO27Q2", "Gigabyte", "旗舰", "27英寸", "OLED电竞显示器"),
    ("Gigabyte FO32U2", "Gigabyte", "旗舰", "32英寸", "OLED电竞显示器"),
    ("AORUS CO49DQ", "AORUS", "旗舰", "49英寸", "超宽曲面电竞显示器"),
    ("Acer Nitro VG240Y", "Nitro", "入门", "24英寸", "电竞显示器"),
    ("Acer Nitro VG270", "Nitro", "入门", "27英寸", "电竞显示器"),
    ("Acer Nitro VG271U", "Nitro", "中端", "27英寸", "电竞显示器"),
    ("Acer Nitro VG272U", "Nitro", "中端", "27英寸", "电竞显示器"),
    ("Acer Nitro VG280K", "Nitro", "中端", "28英寸", "电竞显示器"),
    ("Acer Nitro VG321QU", "Nitro", "中高端", "32英寸", "电竞显示器"),
    ("Acer Nitro VG340", "Nitro", "中高端", "34英寸", "曲面电竞显示器"),
    ("Acer Predator XB241H", "Predator", "中端", "24英寸", "电竞显示器"),
    ("Acer Predator XB251Q", "Predator", "中端", "25英寸", "电竞显示器"),
    ("Acer Predator XB253Q", "Predator", "中端", "25英寸", "电竞显示器"),
    ("Acer Predator XB271HU", "Predator", "中高端", "27英寸", "电竞显示器"),
    ("Acer Predator XB273K", "Predator", "高端", "27英寸", "电竞显示器"),
    ("Acer Predator XB273U GS", "Predator", "高端", "27英寸", "电竞显示器"),
    ("Acer Predator XB273U GX", "Predator", "高端", "27英寸", "电竞显示器"),
    ("Acer Predator XB283K", "Predator", "中高端", "28英寸", "电竞显示器"),
    ("Acer Predator XB323QK", "Predator", "高端", "32英寸", "电竞显示器"),
    ("Acer Predator X34 GS", "Predator", "高端", "34英寸", "曲面电竞显示器"),
    ("Acer Predator X38 S", "Predator", "旗舰", "38英寸", "曲面电竞显示器"),
    ("Acer Predator X45", "Predator", "旗舰", "45英寸", "OLED曲面电竞显示器"),
    ("Acer Predator X49", "Predator", "旗舰", "49英寸", "超宽曲面电竞显示器"),
    ("BenQ ZOWIE XL2411K", "ZOWIE", "中端", "24英寸", "电竞显示器"),
    ("BenQ ZOWIE XL2540K", "ZOWIE", "中端", "25英寸", "电竞显示器"),
    ("BenQ ZOWIE XL2546K", "ZOWIE", "中高端", "25英寸", "电竞显示器"),
    ("BenQ ZOWIE XL2546X", "ZOWIE", "中高端", "25英寸", "电竞显示器"),
    ("BenQ ZOWIE XL2566K", "ZOWIE", "高端", "25英寸", "电竞显示器"),
    ("BenQ ZOWIE XL2566X", "ZOWIE", "高端", "25英寸", "电竞显示器"),
    ("BenQ ZOWIE XL2746S", "ZOWIE", "高端", "27英寸", "电竞显示器"),
    ("BenQ ZOWIE XL2720Z", "ZOWIE", "中端", "27英寸", "电竞显示器"),
    ("BenQ MOBIUZ EX2510S", "BenQ", "中端", "25英寸", "电竞显示器"),
    ("BenQ MOBIUZ EX2710Q", "BenQ", "中高端", "27英寸", "电竞显示器"),
    ("BenQ MOBIUZ EX2710U", "BenQ", "高端", "27英寸", "电竞显示器"),
    ("BenQ MOBIUZ EX3210U", "BenQ", "高端", "32英寸", "电竞显示器"),
    ("BenQ PD2705U", "BenQ", "高端", "27英寸", "办公显示器"),
    ("BenQ PD3220U", "BenQ", "高端", "32英寸", "办公显示器"),
    ("BenQ RD280U", "BenQ", "中高端", "28英寸", "办公显示器"),
    ("BenQ SW321C", "BenQ", "旗舰", "32英寸", "办公显示器"),
    ("HP Omen 24", "Omen", "入门", "24英寸", "电竞显示器"),
    ("HP Omen 25", "Omen", "入门", "25英寸", "电竞显示器"),
    ("HP Omen 27", "Omen", "中端", "27英寸", "电竞显示器"),
    ("HP Omen 27q", "Omen", "中端", "27英寸", "电竞显示器"),
    ("HP Omen 27i", "Omen", "中高端", "27英寸", "电竞显示器"),
    ("HP Omen 27qs", "Omen", "中高端", "27英寸", "电竞显示器"),
    ("HP Omen 32q", "Omen", "中高端", "32英寸", "电竞显示器"),
    ("HP Omen X 27", "Omen", "高端", "27英寸", "电竞显示器"),
    ("HP Omen Transcend 32", "Omen", "旗舰", "32英寸", "OLED电竞显示器"),
    ("HP Omen Transcend 32 UHD", "Omen", "旗舰", "32英寸", "OLED电竞显示器"),
    ("HP E24 G4", "HP", "入门", "24英寸", "办公显示器"),
    ("HP E27 G5", "HP", "中端", "27英寸", "办公显示器"),
    ("ViewSonic XG2405", "ViewSonic", "入门", "24英寸", "电竞显示器"),
    ("ViewSonic XG2431", "ViewSonic", "中端", "24英寸", "电竞显示器"),
    ("ViewSonic XG2506", "ViewSonic", "中端", "25英寸", "电竞显示器"),
    ("ViewSonic XG270", "ViewSonic", "中端", "27英寸", "电竞显示器"),
    ("ViewSonic XG2705", "ViewSonic", "中端", "27英寸", "电竞显示器"),
    ("ViewSonic XG270QG", "ViewSonic", "中高端", "27英寸", "电竞显示器"),
    ("ViewSonic XG321UG", "ViewSonic", "高端", "32英寸", "电竞显示器"),
    ("ViewSonic XG340-2K", "ViewSonic", "中高端", "34英寸", "曲面电竞显示器"),
    ("ViewSonic XG341C-2K", "ViewSonic", "中高端", "34英寸", "曲面电竞显示器"),
    ("ViewSonic VX2418", "ViewSonic", "入门", "24英寸", "办公显示器"),
    ("ViewSonic VX2718", "ViewSonic", "入门", "27英寸", "办公显示器"),
    ("ViewSonic VX2758", "ViewSonic", "入门", "27英寸", "办公显示器"),
    ("ViewSonic VX3211", "ViewSonic", "中端", "32英寸", "办公显示器"),
    ("Philips Evnia 24M1N3200Z", "Philips", "入门", "24英寸", "电竞显示器"),
    ("Philips Evnia 27M1N3200Z", "Philips", "入门", "27英寸", "电竞显示器"),
    ("Philips Evnia 27M1N5500", "Philips", "中端", "27英寸", "电竞显示器"),
    ("Philips Evnia 27M1N5500P", "Philips", "中端", "27英寸", "电竞显示器"),
    ("Philips Evnia 27M2N5500", "Philips", "中高端", "27英寸", "电竞显示器"),
    ("Philips Evnia 32M1N5800", "Philips", "中高端", "32英寸", "电竞显示器"),
    ("Philips Evnia 34M2C8600", "Philips", "旗舰", "34英寸", "OLED曲面电竞显示器"),
    ("Philips Evnia 49M2C8900", "Philips", "旗舰", "49英寸", "超宽曲面电竞显示器"),
    ("Philips 27M2N3200", "Philips", "中端", "27英寸", "电竞显示器"),
    ("Philips 34M1C5500V", "Philips", "中端", "34英寸", "曲面电竞显示器"),
    ("KTC H27T22", "KTC", "中端", "27英寸", "电竞显示器"),
    ("KTC H27T22S", "KTC", "中端", "27英寸", "电竞显示器"),
    ("KTC H27E22", "KTC", "中端", "27英寸", "电竞显示器"),
    ("KTC H27V22", "KTC", "中端", "27英寸", "曲面电竞显示器"),
    ("KTC H32S17", "KTC", "中端", "32英寸", "曲面电竞显示器"),
    ("KTC M27T20", "KTC", "中高端", "27英寸", "电竞显示器"),
    ("KTC G27P6", "KTC", "高端", "27英寸", "OLED电竞显示器"),
    ("KTC G34P5", "KTC", "中高端", "34英寸", "曲面电竞显示器"),
    ("KTC G42P5", "KTC", "旗舰", "42英寸", "OLED电竞显示器"),
    ("Xiaomi Mi Monitor G24", "Xiaomi", "入门", "24英寸", "电竞显示器"),
    ("Xiaomi Mi Monitor G27", "Xiaomi", "入门", "27英寸", "电竞显示器"),
    ("Xiaomi Mi Monitor G27Q", "Xiaomi", "中端", "27英寸", "电竞显示器"),
    ("Xiaomi Mi Monitor G27Qi", "Xiaomi", "中端", "27英寸", "电竞显示器"),
    ("Xiaomi Mi Curved Monitor 34", "Xiaomi", "中端", "34英寸", "曲面电竞显示器"),
    ("Xiaomi Mi Surface Display 34", "Xiaomi", "中高端", "34英寸", "曲面办公显示器"),
    ("Xiaomi Mi Monitor 27 4K", "Xiaomi", "中高端", "27英寸", "办公显示器"),
    ("Redmi Monitor G27Q", "Redmi", "中端", "27英寸", "电竞显示器"),
    ("HKC MG24Q", "HKC", "中端", "24英寸", "电竞显示器"),
    ("HKC MG27Q", "HKC", "中端", "27英寸", "电竞显示器"),
    ("HKC MG27U", "HKC", "中高端", "27英寸", "电竞显示器"),
    ("HKC PG27P3Q", "HKC", "中端", "27英寸", "电竞显示器"),
    ("HKC VG27", "HKC", "入门", "27英寸", "电竞显示器"),
    ("HKC IG27Q", "HKC", "中端", "27英寸", "电竞显示器"),
    ("HKC SG32QC", "HKC", "中端", "32英寸", "曲面电竞显示器"),
    ("HKC CG32S", "HKC", "中端", "32英寸", "曲面电竞显示器"),
    ("Innocn 27G1S", "Innocn", "中端", "27英寸", "电竞显示器"),
    ("Innocn 27G1Q", "Innocn", "中端", "27英寸", "电竞显示器"),
    ("Innocn 27M2V", "Innocn", "高端", "27英寸", "电竞显示器"),
    ("Innocn 27M2U", "Innocn", "中高端", "27英寸", "办公显示器"),
    ("Innocn 32M2V", "Innocn", "高端", "32英寸", "电竞显示器"),
    ("Innocn 34G1S", "Innocn", "中高端", "34英寸", "曲面电竞显示器"),
]

CHAIRS = [
    ("Secretlab Titan Evo 2020", "Secretlab", "中高端", "电竞椅"),
    ("Secretlab Titan Evo 2022", "Secretlab", "中高端", "电竞椅"),
    ("Secretlab Titan Evo 2024", "Secretlab", "高端", "电竞椅"),
    ("Secretlab Titan Evo XL", "Secretlab", "高端", "电竞椅"),
    ("Secretlab Titan Evo NanoGen", "Secretlab", "高端", "电竞椅"),
    ("Secretlab Titan Evo SoftWeave", "Secretlab", "中高端", "电竞椅"),
    ("Secretlab Titan Evo NAPA", "Secretlab", "高端", "电竞椅"),
    ("Secretlab Titan Evo PU", "Secretlab", "中高端", "电竞椅"),
    ("Secretlab Omega 2020", "Secretlab", "中端", "电竞椅"),
    ("Secretlab Classic 2020", "Secretlab", "中端", "电竞椅"),
    ("Herman Miller Aeron Size A", "Herman Miller", "高端", "人体工学椅"),
    ("Herman Miller Aeron Size B", "Herman Miller", "高端", "人体工学椅"),
    ("Herman Miller Aeron Size C", "Herman Miller", "高端", "人体工学椅"),
    ("Herman Miller Embody", "Herman Miller", "旗舰", "人体工学椅"),
    ("Herman Miller Embody Gaming", "Herman Miller", "旗舰", "人体工学椅"),
    ("Herman Miller Sayl", "Herman Miller", "中高端", "人体工学椅"),
    ("Herman Miller Mirra 2", "Herman Miller", "高端", "人体工学椅"),
    ("Herman Miller Cosm", "Herman Miller", "旗舰", "人体工学椅"),
    ("Herman Miller Lino", "Herman Miller", "中高端", "人体工学椅"),
    ("Herman Miller Caper", "Herman Miller", "中端", "办公椅"),
    ("Steelcase Gesture", "Steelcase", "旗舰", "人体工学椅"),
    ("Steelcase Leap V2", "Steelcase", "高端", "人体工学椅"),
    ("Steelcase Series 1", "Steelcase", "中端", "人体工学椅"),
    ("Steelcase Series 2", "Steelcase", "中高端", "人体工学椅"),
    ("Steelcase Amia", "Steelcase", "中高端", "人体工学椅"),
    ("Steelcase Please V2", "Steelcase", "中高端", "人体工学椅"),
    ("Steelcase Karman", "Steelcase", "旗舰", "人体工学椅"),
    ("Steelcase Think", "Steelcase", "中高端", "人体工学椅"),
    ("Steelcase Ology", "Steelcase", "旗舰", "人体工学椅"),
    ("Humanscale Freedom", "Humanscale", "旗舰", "人体工学椅"),
    ("Humanscale Liberty", "Humanscale", "高端", "人体工学椅"),
    ("Humanscale Diffrient World", "Humanscale", "高端", "人体工学椅"),
    ("Humanscale Smart", "Humanscale", "中高端", "人体工学椅"),
    ("Razer Iskur V2", "Razer", "中高端", "电竞椅"),
    ("Razer Iskur V2 X", "Razer", "中端", "电竞椅"),
    ("Razer Iskur X", "Razer", "中端", "电竞椅"),
    ("Razer Enki", "Razer", "中高端", "电竞椅"),
    ("Razer Enki Pro", "Razer", "高端", "电竞椅"),
    ("Razer Enki Pro HyperSense", "Razer", "旗舰", "电竞椅"),
    ("Corsair T3 Rush", "Corsair", "中端", "电竞椅"),
    ("Corsair T3 Rush XL", "Corsair", "中高端", "电竞椅"),
    ("Corsair T2", "Corsair", "中端", "电竞椅"),
    ("Corsair TC100 Relaxed", "Corsair", "中端", "电竞椅"),
    ("Corsair TC100 Fabric", "Corsair", "中端", "电竞椅"),
    ("AndaSeat Kaiser 2", "AndaSeat", "中高端", "电竞椅"),
    ("AndaSeat Kaiser 3", "AndaSeat", "高端", "电竞椅"),
    ("AndaSeat Markus", "AndaSeat", "中端", "电竞椅"),
    ("AndaSeat Phantom", "AndaSeat", "中端", "电竞椅"),
    ("AndaSeat Fnatic Edition", "AndaSeat", "高端", "电竞椅"),
    ("AndaSeat T-Clamp Master", "AndaSeat", "旗舰", "电竞椅"),
    ("AndaSeat AD12", "AndaSeat", "中端", "电竞椅"),
    ("AndaSeat Tilt", "AndaSeat", "中端", "电竞椅"),
    ("DXRacer Master", "DXRacer", "中高端", "电竞椅"),
    ("DXRacer King", "DXRacer", "中高端", "电竞椅"),
    ("DXRacer Racing", "DXRacer", "中端", "电竞椅"),
    ("DXRacer Air", "DXRacer", "中高端", "电竞椅"),
    ("DXRacer Formula", "DXRacer", "中端", "电竞椅"),
    ("DXRacer Craft", "DXRacer", "中高端", "电竞椅"),
    ("DXRacer G-Series", "DXRacer", "中端", "电竞椅"),
    ("DXRacer Classic", "DXRacer", "入门", "电竞椅"),
    ("Noblechairs Epic", "Noblechairs", "中高端", "电竞椅"),
    ("Noblechairs Epic Real Leather", "Noblechairs", "高端", "电竞椅"),
    ("Noblechairs Hero", "Noblechairs", "中高端", "电竞椅"),
    ("Noblechairs Hero X", "Noblechairs", "高端", "电竞椅"),
    ("Noblechairs Legend", "Noblechairs", "中高端", "电竞椅"),
    ("Noblechairs Icon", "Noblechairs", "中高端", "电竞椅"),
    ("Noblechairs Tex", "Noblechairs", "中端", "电竞椅"),
    ("Noblechairs Plush", "Noblechairs", "高端", "电竞椅"),
    ("Autonomous ErgoChair Pro", "Autonomous", "中高端", "人体工学椅"),
    ("Autonomous ErgoChair Pro+", "Autonomous", "高端", "人体工学椅"),
    ("Autonomous ErgoChair 2", "Autonomous", "中端", "人体工学椅"),
    ("Autonomous MyoChair", "Autonomous", "中端", "人体工学椅"),
    ("Autonomous Kinn Chair", "Autonomous", "中高端", "人体工学椅"),
    ("Branch Ergonomic Chair", "Branch", "中高端", "人体工学椅"),
    ("Branch Verve", "Branch", "中端", "人体工学椅"),
    ("Branch Task", "Branch", "中端", "办公椅"),
    ("Branch Former", "Branch", "中端", "办公椅"),
    ("Sihoo M18", "Sihoo", "入门", "人体工学椅"),
    ("Sihoo M57", "Sihoo", "入门", "人体工学椅"),
    ("Sihoo M60", "Sihoo", "入门", "人体工学椅"),
    ("Sihoo Doro C300", "Sihoo", "中端", "人体工学椅"),
    ("Sihoo Doro S300", "Sihoo", "中端", "人体工学椅"),
    ("Sihoo Doro C500", "Sihoo", "中高端", "人体工学椅"),
    ("Sihoo Doro S100", "Sihoo", "中端", "人体工学椅"),
    ("Sihoo V1", "Sihoo", "中端", "人体工学椅"),
    ("Hbada E3", "Hbada", "入门", "人体工学椅"),
    ("Hbada E2", "Hbada", "入门", "人体工学椅"),
    ("Hbada A6", "Hbada", "入门", "人体工学椅"),
    ("Hbada O3", "Hbada", "入门", "人体工学椅"),
    ("Hbada H16", "Hbada", "入门", "办公椅"),
    ("Hbada H31", "Hbada", "入门", "办公椅"),
    ("Hbada T3", "Hbada", "入门", "办公椅"),
    ("Hbada H13", "Hbada", "入门", "办公椅"),
    ("IKEA Markus", "IKEA", "中端", "办公椅"),
    ("IKEA Matchspel", "IKEA", "中端", "办公椅"),
    ("IKEA Jarvfjället", "IKEA", "中端", "办公椅"),
    ("IKEA Hattefjäll", "IKEA", "中端", "办公椅"),
    ("IKEA Millberget", "IKEA", "入门", "办公椅"),
    ("IKEA Flisberg", "IKEA", "入门", "办公椅"),
    ("IKEA Alefjäll", "IKEA", "入门", "办公椅"),
    ("IKEA Uppspel", "IKEA", "中端", "办公椅"),
    ("ErgoTune Supreme", "ErgoTune", "中高端", "人体工学椅"),
    ("ErgoTune V2", "ErgoTune", "中高端", "人体工学椅"),
    ("WorkPro Quantum 9000", "WorkPro", "中端", "人体工学椅"),
    ("WorkPro Quantum 12000", "WorkPro", "中高端", "人体工学椅"),
    ("Goplus Ergonomic Chair", "Goplus", "入门", "人体工学椅"),
    ("Hon Ignition 2.0", "Hon", "中端", "办公椅"),
    ("Lorell High-Back Chair", "Lorell", "入门", "办公椅"),
    ("Amazon Basics Ergonomic Chair", "Amazon Basics", "入门", "办公椅"),
    ("Ergonor Seated Chair", "Ergonor", "中端", "人体工学椅"),
    ("Ergonor Pofit", "Ergonor", "中高端", "人体工学椅"),
    ("Xchair X2", "Xchair", "中高端", "人体工学椅"),
    ("Frost Ergonomic Chair", "Frost", "中端", "人体工学椅"),
    ("Uplift Pursuit Chair", "Uplift", "中高端", "人体工学椅"),
    ("Vari Ergo Chair", "Vari", "中高端", "人体工学椅"),
    ("Stealtho Heavy Duty Gaming Chair", "Stealtho", "中端", "电竞椅"),
]

ACCESSORIES = [
    ("Ergotron LX Monitor Arm", "Ergotron", "中高端", "显示器支架"),
    ("Ergotron LX Dual Monitor Arm", "Ergotron", "高端", "显示器支架"),
    ("Ergotron HX Monitor Arm", "Ergotron", "高端", "显示器支架"),
    ("Ergotron MXV Desk Monitor Arm", "Ergotron", "中高端", "显示器支架"),
    ("Ergotron Neo Flex Monitor Arm", "Ergotron", "中高端", "显示器支架"),
    ("Ergotron LX Sit-Stand Desk Mount", "Ergotron", "高端", "显示器支架"),
    ("Ergotron 45-241 Monitor Arm", "Ergotron", "中高端", "显示器支架"),
    ("Ergotron 45-384 Dual Arm", "Ergotron", "高端", "显示器支架"),
    ("Ergotron 45-475 Wall Mount", "Ergotron", "中端", "显示器支架"),
    ("Loctek D7 Monitor Arm", "Loctek", "中端", "显示器支架"),
    ("Loctek D5 Monitor Arm", "Loctek", "中端", "显示器支架"),
    ("North Bayou F80 Monitor Arm", "North Bayou", "入门", "显示器支架"),
    ("North Bayou F100 Monitor Arm", "North Bayou", "入门", "显示器支架"),
    ("North Bayou G40 Monitor Arm", "North Bayou", "入门", "显示器支架"),
    ("VIVO Single Monitor Arm", "VIVO", "入门", "显示器支架"),
    ("VIVO Dual Monitor Arm", "VIVO", "中端", "显示器支架"),
    ("HUANUO Single Monitor Arm", "HUANUO", "入门", "显示器支架"),
    ("HUANUO Dual Monitor Arm", "HUANUO", "中端", "显示器支架"),
    ("Amazon Basics Single Monitor Arm", "Amazon Basics", "入门", "显示器支架"),
    ("Amazon Basics Dual Monitor Arm", "Amazon Basics", "中端", "显示器支架"),
    ("BenQ ScreenBar", "BenQ ScreenBar", "中端", "显示器挂灯"),
    ("BenQ ScreenBar Plus", "BenQ ScreenBar", "中高端", "显示器挂灯"),
    ("BenQ ScreenBar Pro", "BenQ ScreenBar", "中高端", "显示器挂灯"),
    ("BenQ ScreenBar Halo", "BenQ ScreenBar", "高端", "显示器挂灯"),
    ("Xiaomi Monitor Light Bar", "Xiaomi", "入门", "显示器挂灯"),
    ("Baseus Monitor Light Bar", "Baseus", "入门", "显示器挂灯"),
    ("Yeelight Monitor Light Bar", "Yeelight", "入门", "显示器挂灯"),
    ("Elgato Key Light", "Elgato", "中高端", "补光灯"),
    ("Elgato Key Light Mini", "Elgato", "中端", "补光灯"),
    ("Logitech C270", "Logitech", "入门", "摄像头"),
    ("Logitech C310", "Logitech", "入门", "摄像头"),
    ("Logitech C505", "Logitech", "入门", "摄像头"),
    ("Logitech C920", "Logitech", "中端", "摄像头"),
    ("Logitech C922", "Logitech", "中端", "摄像头"),
    ("Logitech C925e", "Logitech", "中端", "摄像头"),
    ("Logitech C930e", "Logitech", "中高端", "摄像头"),
    ("Logitech Brio 100", "Logitech", "中端", "摄像头"),
    ("Logitech Brio 4K", "Logitech", "中高端", "摄像头"),
    ("Logitech Brio 505", "Logitech", "中高端", "摄像头"),
    ("Logitech StreamCam", "Logitech", "中高端", "摄像头"),
    ("Elgato Facecam", "Elgato", "中高端", "摄像头"),
    ("Elgato Facecam Pro", "Elgato", "旗舰", "摄像头"),
    ("Razer Kiyo", "Razer", "中端", "摄像头"),
    ("Razer Kiyo Pro", "Razer", "中高端", "摄像头"),
    ("Razer Kiyo Pro Ultra", "Razer", "旗舰", "摄像头"),
    ("Insta360 Link", "Insta360", "高端", "摄像头"),
    ("Anker PowerConf C200", "Anker", "中端", "摄像头"),
    ("Papalook PA930", "Papalook", "入门", "摄像头"),
    ("Mevo Start", "Mevo", "中高端", "摄像头"),
    ("Rode PSA1", "Rode", "中端", "麦克风支架"),
    ("Rode PSA1+", "Rode", "中端", "麦克风支架"),
    ("Rode PSA1-R", "Rode", "中端", "麦克风支架"),
    ("Rode DS1", "Rode", "入门", "麦克风支架"),
    ("Elgato Wave Mic Arm", "Elgato", "中端", "麦克风支架"),
    ("Elgato Wave Mic Arm LP", "Elgato", "中高端", "麦克风支架"),
    ("Blue Compass", "Blue", "中高端", "麦克风支架"),
    ("Fifine SC600", "Fifine", "入门", "麦克风支架"),
    ("Fifine SC660", "Fifine", "入门", "麦克风支架"),
    ("Innogear Mic Arm", "Innogear", "入门", "麦克风支架"),
    ("Gator Frameworks Mic Arm", "Gator Frameworks", "中端", "麦克风支架"),
    ("Neewer Mic Arm", "Neewer", "入门", "麦克风支架"),
    ("Amazon Basics Mic Arm", "Amazon Basics", "入门", "麦克风支架"),
    ("Razer Base Station", "Razer", "中端", "耳机架"),
    ("Razer Base Station Chroma", "Razer", "中高端", "耳机架"),
    ("Corsair ST100", "Corsair", "中高端", "耳机架"),
    ("SteelSeries Arctis Stand", "SteelSeries", "中端", "耳机架"),
    ("NZXT Puck", "NZXT", "入门", "耳机架"),
    ("HyperX Headset Stand", "HyperX", "入门", "耳机架"),
    ("Redragon Headset Stand", "Redragon", "入门", "耳机架"),
    ("NexiGo Headset Stand", "NexiGo", "入门", "耳机架"),
    ("Lamicall Headset Stand", "Lamicall", "入门", "耳机架"),
    ("Govee Headset Stand", "Govee", "入门", "耳机架"),
    ("ZOWIE Camade II", "ZOWIE", "中端", "鼠标线夹"),
    ("Razer Mouse Bungee V3", "Razer", "中端", "鼠标线夹"),
    ("Glorious Mouse Bungee", "Glorious", "中端", "鼠标线夹"),
    ("Corsair MM1000", "Corsair", "中高端", "鼠标充电垫"),
    ("Logitech PowerPlay", "Logitech", "高端", "鼠标充电垫"),
    ("Razer Mouse Dock Pro", "Razer", "中高端", "鼠标充电底座"),
    ("Razer Mouse Dock Chroma", "Razer", "中端", "鼠标充电底座"),
    ("Razer Viper Mini Signature Dock", "Razer", "高端", "鼠标充电底座"),
    ("CableMod Pro Coiled Cable", "CableMod", "中端", "线材"),
    ("Keychron Coiled Cable", "Keychron", "中端", "线材"),
    ("Glorious Coiled Cable", "Glorious", "中端", "线材"),
    ("Ugreen Braided USB Cable", "Ugreen", "入门", "线材"),
    ("Anker PowerLine USB-C", "Anker", "入门", "线材"),
    ("Baseus Braided Cable", "Baseus", "入门", "线材"),
    ("Nekteck USB Cable", "Nekteck", "入门", "线材"),
    ("Belkin Braided Cable", "Belkin", "入门", "线材"),
    ("Vention USB Cable", "Vention", "入门", "线材"),
    ("JSAUX USB Cable", "JSAUX", "入门", "线材"),
    ("Cable Matters USB-C Cable", "Cable Matters", "入门", "线材"),
    ("Cable Matters Cable Sleeve", "Cable Matters", "入门", "理线"),
    ("VIVO Desk Grommet", "VIVO", "入门", "理线"),
    ("Ugreen Cable Clips", "Ugreen", "入门", "理线"),
    ("3M Command Cable Clips", "3M", "入门", "理线"),
    ("VELCRO Cable Ties", "VELCRO", "入门", "理线"),
    ("Nite Ize Gear Tie", "Nite Ize", "入门", "理线"),
    ("GMK Red Samurai Keycaps", "GMK", "高端", "键帽"),
    ("GMK Bingsu Keycaps", "GMK", "高端", "键帽"),
    ("GMK Dracula Keycaps", "GMK", "高端", "键帽"),
    ("GMK Olivia Keycaps", "GMK", "高端", "键帽"),
    ("GMK White on Black Keycaps", "GMK", "中高端", "键帽"),
    ("GMK Laser Keycaps", "GMK", "高端", "键帽"),
    ("GMK Striker Keycaps", "GMK", "高端", "键帽"),
    ("GMK Metropolis Keycaps", "GMK", "高端", "键帽"),
    ("GMK Handarbeit Keycaps", "GMK", "高端", "键帽"),
    ("GMK Honor Keycaps", "GMK", "高端", "键帽"),
    ("GMK Modo Light Keycaps", "GMK", "高端", "键帽"),
    ("GMK Bento Keycaps", "GMK", "高端", "键帽"),
    ("PBTFans BoW Keycaps", "PBTFans", "中端", "键帽"),
    ("PBTFans WoB Keycaps", "PBTFans", "中端", "键帽"),
    ("PBTFans Shuriken Keycaps", "PBTFans", "中端", "键帽"),
    ("Akko ASA Keycaps", "Akko", "入门", "键帽"),
    ("Akko WOB Keycaps", "Akko", "入门", "键帽"),
    ("Keychron OSA Keycaps", "Keychron", "入门", "键帽"),
    ("Ducky PBT Keycaps", "Ducky", "入门", "键帽"),
    ("KBDfans PBT Keycaps", "KBDfans", "中端", "键帽"),
    ("Drop MT3 Susuwatari Keycaps", "Drop", "中高端", "键帽"),
    ("Drop MT3 BoW Keycaps", "Drop", "中高端", "键帽"),
    ("SA Carbon Keycaps", "Signature Plastics", "高端", "键帽"),
    ("SA Bliss Keycaps", "Signature Plastics", "高端", "键帽"),
    ("SA Miami Keycaps", "Signature Plastics", "高端", "键帽"),
    ("EPBT Keycaps", "EPBT", "中端", "键帽"),
    ("IFK Keycaps", "Infinikey", "中高端", "键帽"),
    ("NicePBT Keycaps", "NicePBT", "中端", "键帽"),
    ("Glorious Aura Keycaps", "Glorious", "入门", "键帽"),
    ("HyperX Pudding Keycaps", "HyperX", "入门", "键帽"),
    ("Glorious Wrist Rest", "Glorious", "中端", "手托"),
    ("Corsair MM500 Wrist Rest", "Corsair", "中端", "手托"),
    ("Razer Ergonomic Wrist Rest", "Razer", "中端", "手托"),
    ("Ducky Wrist Rest", "Ducky", "入门", "手托"),
    ("HyperX Wrist Rest", "HyperX", "入门", "手托"),
    ("Logitech Wrist Rest", "Logitech", "入门", "手托"),
    ("Keychron Wooden Wrist Rest", "Keychron", "入门", "手托"),
    ("Glorious Wooden Wrist Rest", "Glorious", "中端", "手托"),
    ("Varmilo Wrist Rest", "Varmilo", "入门", "手托"),
    ("Filco Wrist Rest", "Filco", "中端", "手托"),
    ("Corsair MM300 Wrist Rest", "Corsair", "入门", "手托"),
    ("SteelSeries QcK Wrist Rest", "SteelSeries", "入门", "手托"),
    ("Glorious 3XL Desk Pad", "Glorious", "中端", "桌垫"),
    ("SteelSeries QcK Edge Desk Pad", "SteelSeries", "入门", "桌垫"),
    ("Razer Goliathus Extended Desk Pad", "Razer", "入门", "桌垫"),
    ("Corsair MM350 Desk Pad", "Corsair", "中端", "桌垫"),
    ("HyperX Fury S Desk Pad", "HyperX", "入门", "桌垫"),
    ("Aukey Desk Pad", "Aukey", "入门", "桌垫"),
    ("Reflex Lab Desk Pad", "Reflex Lab", "中端", "桌垫"),
    ("NovelKeys Desk Pad", "NovelKeys", "中端", "桌垫"),
    ("LTTStore Desk Pad", "LTTStore", "中端", "桌垫"),
    ("Varmilo Desk Pad", "Varmilo", "中端", "桌垫"),
    ("Filco Desk Pad", "Filco", "中端", "桌垫"),
    ("Ducky Desk Pad", "Ducky", "入门", "桌垫"),
    ("Elgato HD60 S+", "Elgato", "高端", "采集卡"),
    ("Elgato HD60 X", "Elgato", "高端", "采集卡"),
    ("Elgato 4K60 Pro MK.2", "Elgato", "旗舰", "采集卡"),
    ("Elgato 4K X", "Elgato", "旗舰", "采集卡"),
    ("Elgato Cam Link 4K", "Elgato", "中高端", "采集卡"),
    ("Elgato Cam Link Pro", "Elgato", "高端", "采集卡"),
    ("Razer Ripsaw HD", "Razer", "中高端", "采集卡"),
    ("Razer Ripsaw X", "Razer", "中高端", "采集卡"),
    ("AverMedia Live Gamer 4K", "AverMedia", "旗舰", "采集卡"),
    ("AverMedia Live Gamer Ultra", "AverMedia", "高端", "采集卡"),
    ("AverMedia Live Gamer 2 PLUS", "AverMedia", "中高端", "采集卡"),
    ("MS2130 USB HDMI Capture Card", "MS2130", "入门", "采集卡"),
    ("Elgato Stream Deck", "Elgato", "中高端", "控制台"),
    ("Elgato Stream Deck Mini", "Elgato", "中端", "控制台"),
    ("Elgato Stream Deck XL", "Elgato", "高端", "控制台"),
    ("Elgato Stream Deck+", "Elgato", "高端", "控制台"),
    ("Elgato Stream Deck Pedal", "Elgato", "中高端", "控制台"),
    ("Razer Stream Controller X", "Razer", "中高端", "控制台"),
    ("Loupedeck Live", "Loupedeck", "高端", "控制台"),
    ("TourBox Elite", "TourBox", "高端", "控制台"),
    ("Switch Puller", "Generic", "入门", "键盘工具"),
    ("Keycap Puller", "Generic", "入门", "键盘工具"),
    ("Switch Lubrication Kit", "Generic", "入门", "键盘工具"),
    ("Krytox 205g0", "Krytox", "入门", "键盘工具"),
    ("Switch Opener", "Generic", "入门", "键盘工具"),
    ("JWK Switch Tester", "JWK", "入门", "键盘工具"),
    ("Gateron Switch Sampler", "Gateron", "入门", "键盘工具"),
    ("Kailh Switch Sampler", "Kailh", "入门", "键盘工具"),
    ("Everglide Switch Sampler", "Everglide", "入门", "键盘工具"),
    ("WS Morandi Switch Sampler", "WS", "入门", "键盘工具"),
    ("Ergonofis Footrest", "Ergonofis", "中高端", "脚托"),
    ("Uplift Footrest", "Uplift", "中端", "脚托"),
    ("Ergodriven Topo Footrest", "Ergodriven", "中端", "脚托"),
    ("Amazon Basics Footrest", "Amazon Basics", "入门", "脚托"),
    ("MINDREADER Footrest", "MINDREADER", "入门", "脚托"),
    ("VIVO Footrest", "VIVO", "入门", "脚托"),
    ("DMI Footrest", "DMI", "入门", "脚托"),
    ("aboveTEK Footrest", "aboveTEK", "入门", "脚托"),
    ("VIVO Monitor Riser", "VIVO", "入门", "显示器增高架"),
    ("HUANUO Monitor Riser", "HUANUO", "入门", "显示器增高架"),
    ("Amazon Basics Monitor Riser", "Amazon Basics", "入门", "显示器增高架"),
    ("GreenSunny Monitor Riser", "GreenSunny", "入门", "显示器增高架"),
    ("North Bayou Monitor Riser", "North Bayou", "入门", "显示器增高架"),
    ("Simple Houseware Monitor Riser", "Simple Houseware", "入门", "显示器增高架"),
    ("Mount-It! Monitor Riser", "Mount-It!", "入门", "显示器增高架"),
    ("Loctek Monitor Riser", "Loctek", "入门", "显示器增高架"),
    ("Anker 525 Charger", "Anker", "中端", "电源"),
    ("Anker 727 Charging Station", "Anker", "中高端", "电源"),
    ("Ugreen Charger", "Ugreen", "中端", "电源"),
    ("APC Surge Protector", "APC", "中端", "电源"),
    ("Belkin Surge Protector", "Belkin", "中端", "电源"),
    ("CyberPower Surge Protector", "CyberPower", "中端", "电源"),
    ("Tripp Lite Surge Protector", "Tripp Lite", "中端", "电源"),
    ("Baseus Charger", "Baseus", "中端", "电源"),
    ("Anker 8-in-1 Hub", "Anker", "中端", "扩展坞"),
    ("Anker 10-in-1 Hub", "Anker", "中高端", "扩展坞"),
    ("Ugreen 9-in-1 Hub", "Ugreen", "中高端", "扩展坞"),
    ("CalDigit TS4", "CalDigit", "旗舰", "扩展坞"),
    ("CalDigit TS3 Plus", "CalDigit", "高端", "扩展坞"),
    ("CalDigit Element Hub", "CalDigit", "高端", "扩展坞"),
    ("Satechi Hub", "Satechi", "中高端", "扩展坞"),
    ("Sabrent Hub", "Sabrent", "中端", "扩展坞"),
    ("Baseus Hub", "Baseus", "中端", "扩展坞"),
    ("Rain Design mStand", "Rain Design", "中端", "笔记本支架"),
    ("Ugreen Laptop Stand", "Ugreen", "入门", "笔记本支架"),
    ("Nulaxy Laptop Stand", "Nulaxy", "入门", "笔记本支架"),
    ("Soundance Laptop Stand", "Soundance", "入门", "笔记本支架"),
    ("MOFT Laptop Stand", "MOFT", "入门", "笔记本支架"),
    ("Roost Stand", "Roost", "中高端", "笔记本支架"),
    ("Twelve South Curve", "Twelve South", "中高端", "笔记本支架"),
    ("Lamicall Laptop Stand", "Lamicall", "入门", "笔记本支架"),
    ("Anker Phone Stand", "Anker", "入门", "手机支架"),
    ("Ugreen Phone Stand", "Ugreen", "入门", "手机支架"),
    ("Lamicall Phone Stand", "Lamicall", "入门", "手机支架"),
    ("Spigen Phone Stand", "Spigen", "入门", "手机支架"),
    ("Belkin Phone Stand", "Belkin", "入门", "手机支架"),
    ("Logitech Phone Stand", "Logitech", "入门", "手机支架"),
    ("Ugreen HDMI Cable", "Ugreen", "入门", "视频线材"),
    ("Anker HDMI Cable", "Anker", "入门", "视频线材"),
    ("Belkin HDMI Cable", "Belkin", "入门", "视频线材"),
    ("Amazon Basics HDMI Cable", "Amazon Basics", "入门", "视频线材"),
    ("Vention HDMI Cable", "Vention", "入门", "视频线材"),
    ("Cable Matters DisplayPort Cable", "Cable Matters", "入门", "视频线材"),
    ("JSAUX DisplayPort Cable", "JSAUX", "入门", "视频线材"),
    ("Monoprice DisplayPort Cable", "Monoprice", "入门", "视频线材"),
    ("Zeskit HDMI Cable", "Zeskit", "中端", "视频线材"),
    ("Highwings HDMI Cable", "Highwings", "入门", "视频线材"),
    ("Meze Headphone Cable", "Meze", "中端", "耳机线材"),
    ("Hart Audio Cable", "Hart Audio", "中端", "耳机线材"),
    ("Periapt Cable", "Periapt", "中端", "耳机线材"),
    ("Fog City Audio Cable", "Fog City Audio", "中端", "耳机线材"),
    ("Lunashops Cable", "Lunashops", "入门", "耳机线材"),
    ("8 Core Headphone Cable", "Generic", "入门", "耳机线材"),
    ("Uplift V2 Standing Desk", "Uplift", "高端", "升降桌"),
    ("Fully Jarvis Standing Desk", "Fully", "高端", "升降桌"),
    ("Flexispot E7 Standing Desk", "Flexispot", "中高端", "升降桌"),
    ("Autonomous SmartDesk 2", "Autonomous", "中高端", "升降桌"),
    ("Vari Electric Standing Desk", "Vari", "中高端", "升降桌"),
    ("Fezibo Standing Desk", "Fezibo", "中端", "升降桌"),
    ("ApexDesk Standing Desk", "ApexDesk", "中端", "升降桌"),
    ("Mount-It! Standing Desk", "Mount-It!", "中端", "升降桌"),
]


def build():
    monitors = [mk_item("mon", i, *row) for i, row in enumerate(MONITORS)]
    chairs = [mk_item("chr", i, *row) for i, row in enumerate(CHAIRS)]
    accessories = [mk_item("acc", i, *row) for i, row in enumerate(ACCESSORIES)]

    with open(PRODUCTS_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    data["monitors"] = monitors
    data["chairs"] = chairs
    data["accessories"] = accessories

    counts = {
        "mice": len(data.get("mice", [])),
        "keyboards": len(data.get("keyboards", [])),
        "mousepads": len(data.get("mousepads", [])),
        "headsets": len(data.get("headsets", [])),
        "monitors": len(monitors),
        "chairs": len(chairs),
        "accessories": len(accessories),
    }
    total = sum(counts.values())

    meta = data.setdefault("meta", {})
    meta["dataset_name"] = "GearPick 产品库 v6.0"
    meta["version"] = "6.0"
    meta["updated_at"] = "2026-08-18"
    meta["maintainer"] = "陈昊"
    meta["counts"] = counts
    changelog = meta.setdefault("changelog", [])
    changelog.insert(0, (
        "v6.0（2026-08-18）：新增显示器 {} 款 / 电竞椅 {} 款 / 外设配件 {} 款，"
        "总库 {} 款；新品类沿用公开目录口径，价格与参数待核实。"
    ).format(len(monitors), len(chairs), len(accessories), total))

    with open(PRODUCTS_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print("monitors:", len(monitors))
    print("chairs:", len(chairs))
    print("accessories:", len(accessories))
    print("total:", total)
    print("products.json updated")


if __name__ == "__main__":
    build()
